### PR TITLE
456: Allow the Layer0 API Health check to not require basic auth

### LINKED ISSUE #456: Layer0 API health check HTTP:80/admin/health not allowing EC2 instances to attach to ELB
For `api-refactor` and its descendants

### Expected behavior

When standing up an new layer0 API, the ECS container instances running the API service should be attaching to an ELB and the health check HTTP:80/admin/health should be returning an HTTP 200 response.

### Actual behavior

Instead, we observe that the EC2 instances get attached to the API's ELB, then detach after the health check fails.

### Steps to reproduce the behavior

Stand up an new Layer0 instance and then observe the API service's ELB through the AWS console and note the instance list over time.

### PR DESCRIPTION
**Pull request by jparsons04**
**What does this pull request do?**
The admin endpoint /admin/health should not require basic auth.
The way the fireball controller is coded, even if the ELB health check ping target is changed to TCP:port, the controller will still return an HTTP 401 response. 

This change removes /admin/health and instead creates a new endpoint, /health that will not require basic auth.

**How should this be tested?**
Create a new layer0 instance (as of this writing, include the fix in issue #455). When `l0-setup apply` is run, the instance should come up healthy and the apply should finish without issue.

**Checklist**
~- [ ] Unit tests~
~- [ ] Smoke tests (if applicable)~
~- [ ] System tests (if applicable)~
~- [ ] Documentation (if applicable)~

closes #456

### CODE REVIEW

File: api/main.go [hunk 1]
```diff
@@ -105,6 +104,15 @@ func main() {
 		routes = append(routes, controllers.NewTagController(tagStore).Routes()...)
 		routes = append(routes, controllers.NewTaskController(taskProvider, jobStore, tagStore).Routes()...)
 
+		adminRoutes := controllers.NewAdminController(cfg, Version).Routes()
```
Comment (zpatrick) [inline api/main.go]: This can be simplified:  just make a new endpoint, `/health` with a different controller; there is no need for the health check to be tied to the `admin` controller. Then, `append` the health route to `routes` after the routes have been decorated.

Comment (jparsons04) [reply api/main.go]: Ah! Sure thing. That should be straightforward enough.

File: api/controllers/health.go [hunk 2]
```diff
@@ -0,0 +1,33 @@
+package controllers
+
+import (
+	"github.com/quintilesims/layer0/common/config"
+	"github.com/zpatrick/fireball"
+)
+
+type HealthController struct {
+	Config  config.APIConfig
```
Comment (zpatrick) [inline api/controllers/health.go]: why does it need either of these?

File: api/main.go [hunk 3]
```diff
@@ -114,6 +114,8 @@ func main() {
 			fireball.LogDecorator(),
 			fireball.BasicAuthDecorator(user, pass))
 
+		routes = append(routes, controllers.NewHealthController(cfg, Version).Routes()...)
```
Comment (zpatrick) [inline api/main.go]: this should probably have a comment above, like `// don't decorate health endpoint with auth`

File: api/controllers/health.go (hunk 2 above)
Comment (jparsons04) [reply api/controllers/health.go]: :thinking: I suppose given that the API doesn't have any sort of cli flag or environment variable that corresponds with this function, we wouldn't need to have this. If the API changes in some way that would add a cli flag or env var for this controller, then I would suppose we would need these.

I'll remove them.

File: api/main.go (hunk 3 above)
Comment (jparsons04) [reply api/main.go]: :white_check_mark:
