### PR TITLE
Fix l0-setup apply issue for instances created in another region

### LINKED ISSUE #444: failure to push remote tf state when not using default region
### Expected behavior
tf state should be pushed to s3 bucket in the region specified in l0-setup init

### Actual behavior
the state is pushed to a nonexistent bucket in the default refion (us-west-2), so no remote state is ever saved.

[INFO] Pushing /Users/dmeyer/.layer0/hexeast1/dockercfg.json to s3://layer0-hexeast1-236817160978/terraform/dockercfg.json
BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region

v0.10.3

### PR DESCRIPTION
**Pull request by jparsons04**
**What does this pull request do?**
Issue #444 fixed an issue where terraform state would not be pushed at setup time if the layer0 instance was created in a different region. This change was not applied to the api-refactor branches, so this changes that.

**How should this be tested?**

Run `l0-setup init` and specify an instance in a region other than us-west-2, then `l0-setup apply`

**Checklist**
~- [ ] Unit tests~
~- [ ] Smoke tests (if applicable)~
~- [ ] System tests (if applicable)~
~- [ ] Documentation (if applicable)~

closes #444

### CODE REVIEW

File: setup/command/pull.go [hunk 1]
```diff
@@ -33,3 +62,32 @@ func (f *CommandFactory) Pull() cli.Command {
...
+
+	for _, bucket := range listBucketsOutput.Buckets {
+		bucketName := aws.StringValue(bucket.Name)
+
+		if split := strings.Split(bucketName, "-"); len(split) == 3 && split[0] == "layer0" && split[1] == instanceName {
+			return bucketName, nil
+		}
+	}
+
+	return "", fmt.Errorf("No S3 bucket found for given instance name")
```
Comment (zpatrick) [inline setup/command/pull.go]: [nit] should probably show the instance name with some quotes here: `...No S3 bucket found for instance '%s'", instanceName)`
